# Generated by Django 4.0.3 on 2022-04-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_stock_close_remove_stock_open_stockprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='lastScrape',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
