# Generated by Django 4.0.3 on 2022-05-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_lastscrape'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='logo',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
